### PR TITLE
Issue 21 - migrate command not working

### PR DESCRIPTION
**Pull request by eafarooqi**
- `->rtrim('.php')` should be changed to `->replace('.php', '')` as rtrim destroy the class name if `p` or `h` is the last character of class name.
- Double slash `\\` included in the path, should be replaced with single slash `\`

Fix to this issue: #21 

@DarkGhostHunter Please accept and merge, as the plugin is unusable without this fix

### CODE REVIEW

**Comment by SalemCode8** [comment]
@DarkGhostHunter We need this fix to be able to use the package

**Comment by rudolfbruder** [comment]
@DarkGhostHunter Yeah please approve this pull request

**Comment by rudolfbruder** [comment]
@eafarooqi I tried your fix however what I am ending up with is this:
image
Do you think it's connected to your fix. The settable type does not have \ between the words and therefore it does not work. Any ideas ?

**Comment by DarkGhostHunter** [comment]
I’ll check it on new year. 

Italo Baeza C.

**Pull request merged**
