### PR TITLE
Add static analysis

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please start CI :)

**Comment by szepeviktor** [comment]
@DarkGhostHunter Please consider running static analysis.
https://github.com/szepeviktor/Laraconfig/runs/3106068821?check_suite_focus=true 👀

**Comment by DarkGhostHunter** [comment]
What when why how?

**Comment by szepeviktor** [comment]
As in this PR: https://github.com/DarkGhostHunter/Laraconfig/pull/4/files

1. Install Larastan
2. Run it :)

The above CI output shows some problems/typos/false positives.

**Comment by DarkGhostHunter** [comment]
Thanks but I'm not interested in static analysis... yet (specially when on many false positives and magic methods).

**Pull request closed without merging**
